services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pulseboard
      POSTGRES_PASSWORD: pulseboard
      POSTGRES_DB: pulseboard
    volumes:
      - pulseboard_pg:/var/lib/postgresql/data

volumes:
  pulseboard_pg:
